const timezones = [
    '(GMT-11:00) Midway Island, Samoa',
    '(GMT-10:00) Hawaii',
    '(GMT-8:00) Alaska',
    '(GMT-7:00) Dawson, Yukon',
    '(GMT-7:00) Arizona',
    '(GMT-7:00) Tijuana',
    '(GMT-7:00) Pacific Time',
    '(GMT-6:00) Mountain Time',
    '(GMT-6:00) Chihuahua, La Paz, Mazatan',
    '(GMT-6:00) Saskatchewan',
    '(GMT-6:00) Central America',
    '(GMT-5:00) Central Time',
    '(GMT-5:00) Guadalajara, Mexico City, Monterrey',
    '(GMT-5:00) Bogota, Lima, Quito',
    '(GMT-4:00) Eastern Time',
    '(GMT-4:00) Caracas, La Paz',
    '(GMT-4:00) Santiago',
    '(GMT-3:00) Brasilia',
    '(GMT-3:00) Montevideo',
    '(GMT-3:00) Buenos Aires, Georgetown',
    '(GMT-2:30) Newfoundland and Labrador',
    '(GMT-2:00) Greenland',
    '(GMT-1:00) Cape Verde Islands',
    '(GMT+0:00) Azores',
    '(GMT+0:00) UTC',
    '(GMT+0:00) Casablanca, Monrovia',
    '(GMT+1:00) Edinburgh, London',
    '(GMT+1:00) Dublin',
    '(GMT+1:00) Lisbon',
    '(GMT+1:00) Canary Islands',
    '(GMT+1:00) West Central Africa',
    '(GMT+2:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague',
    '(GMT+2:00) Sarajevo, Skopje, Warsaw, Zagreb',
    '(GMT+2:00) Brussels, Copenhagen, Madrid, Paris',
    '(GMT+2:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna',
    '(GMT+2:00) Cairo',
    '(GMT+2:00) Harare, Pretoria',
    '(GMT+3:00) Bucharest',
    '(GMT+3:00) Helsinki, Kyiv, Kyiv, Riga, Sofia, Tallin, Vilnius',
    '(GMT+3:00) Athens, Minsk',
    '(GMT+3:00) Jerusalem',
    '(GMT+3:00) Istanbul, Moscow, St. Petersburg, Volgograd',
    '(GMT+3:00) Kuwait, Riyadh',
    '(GMT+3:00) Nairobi',
    '(GMT+3:00) Baghdad'
];